### ISSUE TITLE
simplified git config causes remote upstream rewrite on every run

### ISSUE THREAD

**Issue by aschleifer** [vcs-python/vcspull#332]
If I use a simple config entry like:

```
~/test/cvspull:
  mypackage: 'git+ssh://git@gitlab.com/mygroup/mypackage.git'
```

I always see the line about `Updating remote origin`:
```
Updating remote origin (ssh://git@gitlab.com/mygroup/mypackage.git) with git+ssh://git@gitlab.com/mygroup/mypackage.git
```
which then in turn causes a retry of the update.

To fix this issue I have to use a config like this:
```
~/test/cvspull:
  mypackage:
    url: 'git+ssh://git@gitlab.com/mygroup/mypackage.git'
    remotes:
      origin: 'ssh://git@gitlab.com/mygroup/mypackage.git'
```

This then works, but I would like to have a more compact/simplified config with only one line per repo.

(repogroup and name have been abstracted, as the used gitlab is internal ;) )

Best regards
Segaja
