### ISSUE TITLE
Config format

### ISSUE THREAD

**Issue by tony** [vcs-python/vcspull#360]
### Eliminate shorthands 

```yaml
<folder>:
  <repoName>: '<repoUrl>'
```

- This would need to be a 2.0.0 thing
- 2.0 could be released today if I wanted to, but we'd end up having versions like Firefox or Chrome does. Eventually we'd end up at vcspull 42.0.1

### One config format

- Has to work with all theoretically all vcs and copying systems: git, svn, hg, scp, rsync, http, whatever

```yaml
<folder>:
  <repoName>:
    vcs: 'git'
    options:
      origin: 
        fetch: '<repoUrl>'
  MySVNProject:
    vcs: 'svn'
    origin: '<repoUrl>'
```

**Comment by Segaja** [comment]
Do we really need to rework the config structure? As far as I see the `extract_repos()` call just adds some information, but I think the current sync could work without it.

**Comment by Segaja** [comment]
Also in your example the `git` config is a bit redundant if fetch and push urls are the same. Is that explicit to make the coding easier?

**Comment by tony** [comment]
>  Do we really need to rework the config structure? As far as I see the extract_repos() call just adds some information, but I think the current sync could work without it.

I'd like the make sure the code more transparent and clear - maybe you are onto something. Perhaps make a PR?

**Comment by tony** [comment]
> Also in your example the git config is a bit redundant if fetch and push urls are the same. Is that explicit to make the coding easier?

You're right

`git remotes` allows:

```
git remote -v
origin  git+ssh://git@github.com/vcs-python/vcspull.git (fetch)
origin  git+ssh://git@github.com/vcs-python/vcspull.git (push)
```

But normally `git remote add <name> <url>` is sufficient to add to push the `push`+`fetch` mirror.

```yaml
~/work/:
  libtmux:
    vcs: 'git'
    options:
      origin: 
        url: 'https://github.com/vcs-python/vcspull.git'
  libtmux_mirrored_remotes:
    vcs: 'git'
    options:
      origin: 
        fetch: 'https://github.com/vcs-python/vcspull.git'
        push: 'git+ssh//git@github.com/vcs-python/vcspull.git'
```

**Comment by tony** [comment]
My backstory is back when I created tmuxp/vcspull/etc years ago. I took a lot of inspiration from a config management tool called [salt states](https://docs.saltproject.io/en/latest/ref/states/all/index.html), see their [git](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.git.html#module-salt.states.git).

The more "magic" and "hydration" there is, the more pain it is to debug.

you're feedback is very welcome.  I'm easy either way - I just want to make the code clear and bloat-free as possible

**Comment by Segaja** [comment]
> > Do we really need to rework the config structure? As far as I see the extract_repos() call just adds some information, but I think the current sync could work without it.
> 
> I'd like the make sure the code more transparent and clear - maybe you are onto something. Perhaps make a PR?

I'm trying. I'm not sure if I want the path expansion to happen during config loading or when we loop over the entries anyway to update them.

**Comment by tony** [comment]
> I'm trying. I'm not sure if I want the path expansion to happen during config loading or when we loop over the entries anyway to update them.

Chicken or egg.

**Comment by Segaja** [comment]
```yaml
~/work/:
  libtmux:
    vcs: 'git'
    remotes:
      origin: 'https://github.com/vcs-python/vcspull.git'
  libtmux_mirrored_remotes:
    vcs: 'git'
    remotes:
      origin: 'git+ssh//git@github.com/vcs-python/vcspull.git'
      fetch: 'https://github.com/vcs-python/vcspull.git'
  MySVNProject:
    vcs: 'svn'
    url: http://unladen-swallow.googlecode.com/svn/trunk/
```
