### ISSUE TITLE
GitSync: Remotes are broke in vcspull

### ISSUE THREAD

**Issue by tony** [vcs-python/vcspull#425]
See also: https://github.com/vcs-python/libvcs/issues/431

`vcspull 1.17.0, libvcs 0.19.0`

```
libvcs on  master ❯ git remote -v
codeberg        git (fetch)
codeberg        git (push)
gitlab  git (fetch)
gitlab  git (push)
origin  git+ssh://git@github.com/vcs-python/libvcs.git (fetch)
origin  git+ssh://git@github.com/vcs-python/libvcs.git (push)
```

```yaml
libvcs:
  repo: "git+ssh://git@github.com/vcs-python/libvcs.git"
  remotes:
    tony: "git+ssh://git@github.com/tony/libvcs.git"
    gitlab: "git@gitlab.com:vcs-python/libvcs.git"
    codeberg: "git@codeberg.org:vcs-python/libvcs.git"
```
